import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'outline-variant': '#e1bfb5',
        surface: '#fbf9f8',
        background: '#fbf9f8',
        secondary: '#5e5e5e',
        'on-tertiary-container': '#303233',
        'inverse-surface': '#303031',
        'on-tertiary-fixed-variant': '#454747',
        'surface-container': '#efeded',
        outline: '#8d7168',
        'primary-fixed-dim': '#ffb59d',
        'surface-tint': '#ab3500',
        error: '#ba1a1a',
        'on-background': '#1b1c1c',
        'on-tertiary-fixed': '#1a1c1c',
        'primary-container': '#ff6b35',
        'secondary-fixed': '#e2e2e2',
        'inverse-primary': '#ffb59d',
        'secondary-fixed-dim': '#c6c6c6',
        'on-primary-container': '#5f1900',
        'on-primary-fixed-variant': '#832600',
        'on-secondary-fixed': '#1b1b1b',
        'on-surface-variant': '#594139',
        'surface-dim': '#dbdad9',
        'surface-container-high': '#e9e8e7',
        'on-error-container': '#93000a',
        'tertiary-container': '#999a9a',
        'surface-variant': '#e4e2e2',
        'on-secondary': '#ffffff',
        'on-primary': '#ffffff',
        'tertiary-fixed': '#e2e2e2',
        'tertiary-fixed-dim': '#c6c6c7',
        'on-error': '#ffffff',
        'on-tertiary': '#ffffff',
        primary: '#ab3500',
        'surface-container-lowest': '#ffffff',
        'on-secondary-fixed-variant': '#474747',
        'on-surface': '#1b1c1c',
        'surface-bright': '#fbf9f8',
        'error-container': '#ffdad6',
        'primary-fixed': '#ffdbd0',
        'surface-container-highest': '#e4e2e2',
        'surface-container-low': '#f5f3f3',
        'inverse-on-surface': '#f2f0f0',
        'on-secondary-container': '#646464',
        'on-primary-fixed': '#390c00',
        'secondary-container': '#e2e2e2',
        tertiary: '#5d5f5f',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      maxWidth: {
        '6xl': '72rem',
      },
    },
  },
  plugins: [],
};

export default config;
